import '../styles/globals.css';

function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />;
}

export default MyApp;

////////////////////////////////////////////////////////////////////////////////////

// import '../styles/globals.css';
// import Head from 'next/head'
// import Header from '../components/Header'

// function MyApp({ Component, pageProps }) {
//   const [user, setUser] = useState({
//     "provider": null,
//     "signer": null,
//     "signerAddress": null,
//   })
//   const [contracts, setContracts] = useState({
//       "uloanContract": null,
//       "stablecoinContract": null
//   })
//   useEffect(() => {
//     if (user.signer){
//       connectContracts()
//     }
//   }, [])

//   async function connectContracts() {
//     // address from local host
//     const uloanContract = new ethers.Contract("0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512", uloanAbi, user.signer);
//     // Get Stablecoin ERC20 address
//     const tokenAddress = await uloanContract.stablecoin();
//     // const tokenAddress = '';  // Public Testnet
//     const stablecoinContract = new ethers.Contract(tokenAddress, stablecoinAbi, user.signer);
    
//     setContracts({
//       "uloanContract": uloanContract,
//       "stablecoinContract": stablecoinContract
//     })
//   }

//   async function connectUser() {
//     const web3Modal = new Web3Modal()
//     const connection = await web3Modal.connect()
//     const provider = new ethers.providers.Web3Provider(connection)
//     const signer = provider.getSigner()
    
//     setUser({
//       "provider": provider,
//       "signer": signer,
//       "signerAddress": signer.getAddress(),
//     })
//   }

//   return (
//     <div>
//       <Head>
//         <title>ULoan</title>
//         {/* <meta name="description" content="Generated by create next app" /> */}
//         <link rel='icon' href='/favicon.ico' />
//       </Head>

//       {/* Header */}
//       <Header account={user} setAccount={setUser}></Header>
      
//       <Component {...pageProps} />;
//     </div>
//   )
// }

// export default MyApp;
