import Head from 'next/head';
import Image from 'next/image';
import { Result } from 'postcss';
import Header from '../components/Header';
import Nav from '../components/Nav';
import Tabs from '../components/Tabs';
import styles from '../styles/Home.module.css';
import requests from '../utils/requests';
import { useState, useEffect } from 'react';

export default function Home() {
  const [account, setAccount] = useState(null);
  useEffect(() => {
    async function connect() {
      if (window.ethereum) {
        const accounts = await window.ethereum.enable();
        setAccount(accounts[0]);
      }
    }
    connect();
  }, []);
  return (
    <div>
      <Head>
        <title>ULoan</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Header */}
      <Header account={account} setAccount={setAccount}></Header>
      {/* Nav */}

      <Nav />

      {/* Tabs */}
      <div className='pt-16 px-48'>
        <Tabs account={account} />
      </div>
    </div>
  );
  // export async function getServerSideProps(context) {
  //   const genre = context.query.genre;
  // }
}
