

import { ethers } from "ethers"
import Web3Modal from "web3modal"
import { useState, useEffect } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import { Result } from 'postcss'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Tabs from '../components/Tabs'
import styles from '../styles/Home.module.css'

import ULOAN from '../abis/ULoan.json';
import STABLECOIN from '../abis/Stablecoin.json'

//Addresses of contract. Need to be in environment variables in production
const uloanContractAddr = '0xe7f1725e7734ce288f8367e1bb143e90bb3f0512'
const stablecoinContractAddr = '0x5fbdb2315678afecb367f032d93f642f64180aa3'

export default function Home() {
  const [user, setUser] = useState({
      provider: null,
      signer: null,
      signerAddress: null,
  })
  const [contracts, setContracts] = useState({
      uloanContract: null,
      stablecoinContract: null
  })
  const [account, setAccount] = useState(null);
  useEffect(() => {
    async function connectUser() {  
      if (window.ethereum) {
        // const accounts = await window.ethereum.enable();
        // setAccount(accounts[0]);
        const web3Modal = new Web3Modal()
        const connection = await web3Modal.connect()
        const provider = new ethers.providers.Web3Provider(connection)
        const signer = provider.getSigner()
        const signerAddress = await signer.getAddress()
        setAccount(signerAddress)
     
        console.log("signer: ", signer)
        console.log("user: ", user)
        console.log("provider: ", provider)
        console.log("account: ", account)
      }
    }
    connectUser();
  }, ['account']);
  useEffect(() => {
    connectContracts();
  }, []);
    
  

  async function connectContracts() {  
    if (account) {
      const web3Modal = new Web3Modal()
      const connection = await web3Modal.connect()
      const provider = new ethers.providers.Web3Provider(connection)
      const signer = provider.getSigner()
      const signerAddress = await signer.getAddress()
      // address from local host
      const uloanContract = new ethers.Contract(uloanContractAddr, ULOAN.abi, signer)
      // Get Stablecoin ERC20 address
      const tokenAddress = await uloanContract.stablecoin()
      // const tokenAddress = '';  //Testnet
      const stablecoinContract = new ethers.Contract(tokenAddress, STABLECOIN.abi, signer)
      setUser({
        provider: provider,
        signer: signer,
        signerAddress: signerAddress,
      })
      console.log("setUser info: ", user)
      setContracts({
        uloanContract: uloanContract,
        stablecoinContract: stablecoinContract
      })
      console.log("setContract info: ", contracts)
    }
  }

  return (
    <div>
      <Head>
        <title>ULoan</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Header */}
      <Header account={account} setAccount={setAccount} ></Header>
      {/* Nav */}

      <Nav />

      {/* Tabs */}
      <div className='pt-16 px-48'>
        <Tabs account={account} contracts={contracts} setContracts={setContracts} user={user} setUser={setUser} Tabs/>
      </div>
    </div>
  );
}
// export async function getServerSideProps() {
//   // Fetch data from external API
//   const res = await fetch(`https://.../data`)
//   const data = await res.json()

//   // Pass data to the page via props
//   return { props: { data } }
// }